"""empty message

Revision ID: 9fb8111734a7
Revises: 
Create Date: 2022-08-26 11:51:04.826892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fb8111734a7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dblokasi',
    sa.Column('id_lokasi', sa.Integer(), nullable=False),
    sa.Column('lokasi', sa.String(length=300), nullable=False),
    sa.Column('longitude', sa.String(length=50), nullable=False),
    sa.Column('latitude', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_lokasi')
    )
    op.create_table('dbuser',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=12), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id_user')
    )
    op.create_table('dbdata',
    sa.Column('id_data', sa.Integer(), nullable=False),
    sa.Column('id_lokasi', sa.Integer(), nullable=False),
    sa.Column('pergeseran', sa.Integer(), nullable=False),
    sa.Column('waktu', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_lokasi'], ['dblokasi.id_lokasi'], ),
    sa.PrimaryKeyConstraint('id_data')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dbdata')
    op.drop_table('dbuser')
    op.drop_table('dblokasi')
    # ### end Alembic commands ###
